### ISSUE TITLE
What do you do with the windows binary?

### ISSUE THREAD

**Issue by seanfilidis** [dakusan/PlexPlaylistImporter#1]
How do you make this work on Windows?

I downloaded the windows binary on my Windows Plex machine.

Double clicking the .exe file just makes a DOS prompt window appear and disappear right away. 

How am I supposed to tell it where to look for my .m3u file??

**Comment by dakusan** [comment]
The program has no GUI (graphical user interface). It is a program used
through the command prompt. I might update it soon though to allow
dragging an M3U file onto it for people who don't know how to use a
command line terminal.

Jeff

Hyrulean Productions http://www.castledragmire.com
 ▲
▲ ▲

**Comment by seanfilidis** [comment]
Well, I generally know how to use the command prompt. But how do I enter the parameters the program needs? I assume I change directory to the folder where the .exe is located. Then what? What do I type to run the program from the prompt and with the necessary parameters?

**Comment by dakusan** [comment]
Change the folder to the directory with the executable. Type the
executables name and it will tell you the parameters it wants. Make sure
to enclose paths with quotes. Example:
PlexPlaylistImporter "C:\MyMusic\MyAlbum" "My Album Name"

Jeff

Hyrulean Productions http://www.castledragmire.com
 ▲
▲ ▲

**Comment by seanfilidis** [comment]
Great! Thanks. 
You should include the above instructions in the ReadMe for people like me :)
