### ISSUE TITLE
DB Error: no such collation sequence: naturalsort

### ISSUE THREAD

**Issue by winghugs** [dakusan/PlexPlaylistImporter#16]
Getting the above error when attempting to run. Getting the error in both encoding methods after fixing some "not found" errors and rescanning library. 

Fedora 28 server
Not showing any logs - any ideas?

**Comment by winghugs** [comment]
This can be closed. Fixed per this thread: https://forums.plex.tv/t/database-corruption/236013/23

**Comment by jradwan** [comment]
I just ran into this same problem. Thanks for the link to the sqlite commands to resolve this.

HOWEVER, even if you follow those steps, the problem will come back the next time you start the PMS:

https://forums.plex.tv/t/there-was-an-unexpected-error-loading-this-library/235707/14

"The update for naturalsort would get applied again on launch of Plex Media Server and the database schema update would be re-applied."
