### ISSUE TITLE
DB Error: no such collation sequence: icu_root

### ISSUE THREAD

**Issue by zbourdeau** [dakusan/PlexPlaylistImporter#19]
On the latest version of plex import (with the latest sqllite3.dll file) the import is failing. This is the error I am encountering:

PlexPlaylistImporter.exe PlaylistFile.m3u PlayListFile
Plex playlist is not already created. Would you like to create it now (y/n)? y
DB Error: no such collation sequence: icu_root

Has the DB schema changed?

**Comment by dakusan** [comment]
Marking as duplicate of https://github.com/dakusan/PlexPlaylistImporter/issues/18
