### ISSUE TITLE
ListImporter

### ISSUE THREAD

**Issue by anthonyankrapp** [dakusan/PlexPlaylistImporter#4]
Hi, I have no idea if you're still checking on this project, but I though I'd give it a shot.

I'm attempting to use this to import some .m3u files into Plex. I'm using the .py version with python3 on Raspbian 8.

I've tried several formatting options in the playlist.
1. Relative pathing such as: ../Artist/Album/Disc-Track Song.mp3
2. Absolute pathing such as: /media/Music/Artist/Album/Disc-Track Song.mp3.mp3
3. Same as 1, but in single quotes: '../Artist/Album/Disc-Track Song.mp3.mp3'
4. Same as 2, but in single quotes: '/media/Music/Artist/Album/Disc-Track Song.mp3.mp3'

No matter the format, I always get the same error: ListImporter 'Winamp playlist': Cannot find file listed in playlist (must be relative to the playlist):

I've tested some of the relative pathing to make sure it's correct from the playlist location and they're all fine.

**Comment by dakusan** [comment]
I'm just swamped right now with work so It's hard to find time to answer, but I'll try to help. (There is a lot I need to update on this project too).

Are you using Linux or Windows? If Windows, is it on a share? It's important that the determined absolute path is the same in both Plex, and what my program determines is its full absolute path. But it sounds like it isn't even getting to the matching-with-plex step.

Could you attach one of your placelists with at least 3 entries?

**Comment by anthonyankrapp** [comment]
I understand being busy. There's no rush on any of this, but it's a great idea that I'd love to get working.

My Plex Media Server is hosted on a Raspberry Pi running Raspbian (Debian) Linux.

The attached playlist is in .txt format only because Github doesn't allow upload of .m3u files. On the server it's a .m3u.
[Highfalutin Mix.txt](https://github.com/dakusan/PlexPlaylistImporter/files/217797/Highfalutin.Mix.txt)

**Comment by dakusan** [comment]
First, you need to remove the quotes around the file names.
Second, in your examples, you have a lot of ".mp3.mp3" files. Were those just typos in your example?
Third, try converting the file to Unix format (\n line breaks, as opposed to \r\n). This probably doesn't matter though.
Fourth - Like I said earlier, there is some stuff I haven't updated yet that I need to, especially for linux. Try out [this fork by mattspitz](https://github.com/mattspitz/PlexPlaylistImporter/). I've been meaning to incorporate his code for a while.

**Comment by anthonyankrapp** [comment]
Hi,
I removed all the quotes.
I didn't see any .mp3.mp3 in the file I uploaded or any of the others on the server; must have just been in the example here.
I converted to Unix format (\n line breaks).
I tried the fork by mattspitz.
It's still giving the same "Cannot find file..." error.

**Comment by brooks1man** [comment]
I'm was getting the same error trying to run this script in a FreeBSD jail (via FreeNAS) and the fork by mattspitz fixed it for me.

**Comment by thesatman** [comment]
downloaded the bin version on my Win7 x64 PC. I start the program by doubleclicking PlexPlaylistImporter. I get an popup error telling me that MSVCR100.dll is not installed. It is, located in C:/windows/system32/. To be sure I reinstalled the latest vcredist_x64 and rebooted. Still same problem. What is your advice please?

**Comment by thesatman** [comment]
Will the Windows binary work when Python 2.7 is installed?

**Comment by dakusan** [comment]
Sorry for the very delayed response. I've been trying to get caught up on my backlog. The windows binary will work, as it has the python3.4 dll file in its directory that it hooks into. It ignores preexisting python installs.

**Comment by dakusan** [comment]
Also, are you still having the MSVCR100.dll problem?

**Comment by dakusan** [comment]
Everything requested in this thread should be taken care of with my latest updates. The MSVCR100.dll is written about in the readme file now. I will be uploading a new binary of the software in a few days after I have had another user test it.
