### ISSUE TITLE
Certain playlists imported using this tool gives an error "Playlist not Found"

### ISSUE THREAD

**Issue by IndianBoy42** [dakusan/PlexPlaylistImporter#8]
Basically the title

The album covers show up in the square, but when I try to open it it says "playlist not found"

It seems to occur to random playlists, reimporting doesn't help

Its not content related afaict, nor is it number of item or duration related

**Comment by dakusan** [comment]
Do your playlists have non-standard English alphanumeric characters (A-Z, 0-9)?
Any extra info in the logs (probably not, I never have good luck w/ Plex logs).
If the answer to both of those is no, I may need a copy of your plex database. Or at the very least a list of some of the playlist names that failed.

**Comment by dakusan** [comment]
If I don't hear more on this in 3 days I'll be closing it.
